### ISSUE TITLE
Support Python 3.13

### ISSUE THREAD

**Issue by vengroff** [censusdis/censusdis#300]
**Is your feature request related to a problem? Please describe.**
Python 3.13 is in beta now and is expected to be released Oct 1, 2024. See [PEP-719](https://peps.python.org/pep-0719/) for details. We should ideally support the release as soon as possible.

**Describe the solution you'd like**
- Build a Python 3.13 (ideally a beta, but it depends when we get around to this) virtual env, install dependencies, and run our unit tests.
- Fix whatever issues come up.
- If the issues are in one or more of our dependencies, check if they have scheduled work to support 3.13 and/or file issues against them as appropriate.
- Add 3.13 to the `test-matrix` workflow.

**Describe alternatives you've considered**
We can always wait, but it would be nice to support the latest and greatest version of Python sooner rather than later.

**Additional context**
The longer we wait the higher priority this will become.

**Comment by QuLogic** [comment]
The difficulty here at the moment is that most of your (compiled) dependencies don't have wheels, which will require installing all of their dev dependencies (e.g., gdal for fiona, etc.) and that'll be a lot of work to corral together.

**Comment by vengroff** [comment]
Fair point on the dependencies. Hopefully that becomes less of a problem as we get nearer to the official 3.13 release.

**Comment by arilamstein** [comment]
As an FYI, scipy v1.14.1 added support for Python 3.13: https://scipy.org/news/#scipy-1141-released. 

I just created a branch to try and work on this issue. When I tried to install scipy 1.14.1 I got an error message regarding Python 3.9. Apparently censusdis supports 3.9, but scipy 1.14.1 does not. Due to this mismatch poetry refused to install scipy for me.

So it appears that solving this issue will likely result in censusdis needing to drop support for Python 3.9.

**Comment by vengroff** [comment]
Thanks for working on this @arilamstein . I am looking into getting #316 merged. There is a small problem with tests on windows that I think is completely unrelated and has more to do with the networking env of the github windows machines. I'll figure it out and get this merged.
